### ISSUE TITLE
TVFY emails with policy updates contain dodgy links

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1274] opened 2021-11-04 21:39 UTC
A user has emailed to let us know that the links included in the emails to policy subscribers don't work (i.e. the emails sent out when a policy is updated). After reviewing the emails, I can confirm that they include links that are blocked by my web protection software "due to an unmatching security certificate."

Note that the TVFY pages are fine when you access them through the site itself; it is just the links included in the emails that are dodgy.

**Comment by mlandauer** [comment] 2021-11-04 22:06
@mackaymackay could you please add the body of the email here to make it a little easier for me to see what's happening. Thanks!

**Comment by mackaymackay** [comment] 2021-11-04 22:12
Sure @mlandauer 

Here's a copy of the latest one I received, with links:

Subject line: Policy “for creating a federal Anti-Corruption Commission” updated on They Vote For You

Email body:

> [For creating a federal Anti-Corruption Commission](http://email2.theyvoteforyou.org.au/l2/523178249/4f2a53b38bef48f048a1f8adf232fd3dbff1be5c?url=https%3A%2F%2Ftheyvoteforyou.org.au%2Fpolicies%2F86)
> 
> Added division [Motions - National Integrity Commission - National Integrity Commission Bill 2018 (No. 2)](http://email2.theyvoteforyou.org.au/l2/523178250/61042728c6b3d51a22915f44ebf242997364ce67?url=%2Fdivisions%2Fsenate%2F2021-10-21%2F6). Policy vote set to Yes.
>
> [mackay](http://email2.theyvoteforyou.org.au/l2/523178251/e82e38aeb1e2176d51d3bcb805b81e66c7e7653d?url=https%3A%2F%2Ftheyvoteforyou.org.au%2Fusers%2F3) 4:05PM - 29 Oct 2021
>
> Visit the [policy page](http://email2.theyvoteforyou.org.au/l2/523178249/4f2a53b38bef48f048a1f8adf232fd3dbff1be5c?url=https%3A%2F%2Ftheyvoteforyou.org.au%2Fpolicies%2F86) to unsubscribe from this policy.
>
> [View all your subscriptions](http://email2.theyvoteforyou.org.au/l2/523178252/1acac568ffdf759def926cc9d8e09dcd357badab?url=https%3A%2F%2Ftheyvoteforyou.org.au%2Fusers%2F3%2Fsubscriptions).
>
> Follow [@TheyVote4You](http://email2.theyvoteforyou.org.au/l2/523178253/7f0754a567d383bcf82676bcbd3547ff2dd15403?url=http%3A%2F%2Ftwitter.com%2FTheyVote4You) on Twitter.

**Comment by mlandauer** [comment] 2021-11-04 22:17
@mackaymackay thank you! This looks like a similar problem we've had reported on PlanningAlerts. I can't reproduce the problem directly though I think I know what the problem is related to. What specific operating system and browser version are you using? Also what's the specific security software that's popping up the error?

**Comment by mlandauer** [comment] 2021-11-04 22:18
If I can understand how to reproduce the problem then hopefully I can fix it! 😀

**Comment by mackaymackay** [comment] 2021-11-04 22:20
I'm using bitdefender on Firefox. I just tried the same link in Google Chrome to compare and instead of getting a Bitdefender warning, I got a screen saying "The page you were looking for doesn't exist."

![image](https://user-images.githubusercontent.com/6345406/140428449-50a5bd60-ef78-45a7-98db-15cc74ed3708.png)

**Comment by mlandauer** [comment] 2021-11-04 22:52
@mackaymackay with chrome what's the url in the url bar when that appears. Also, what operating system are you using? Is it windows?

**Comment by mackaymackay** [comment] 2021-11-04 22:55
URL in Chrome: http://email2.theyvoteforyou.org.au/divisions/senate/2021-10-21/6

And yes, sorry, it is Windows I'm using.

**Comment by kat** [comment] 2021-11-05 09:42
I get the same error using firefox on OS X (page you're looking for does not exist)- but only when 'email' is at the head of the URL.

—
Katherine Szuminska

--- original message ---
On November 5, 2021, 9:55 AM GMT+11 ***@***.*** wrote:



URL in Chrome: http://email2.theyvoteforyou.org.au/divisions/senate/2021-10-21/6

And yes, sorry, it is Windows I'm using.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by mlandauer** [comment] 2021-11-05 23:03
@mackaymackay I can see there's a bitdefender "traffic lights" firefox extension https://addons.mozilla.org/en-US/firefox/addon/trafficlight/. Is that the one you're using? Or are you using the paid firewall product? Is it https://www.bitdefender.com/solutions/internet-security.html that you're using? Or one of the others by bitdefender.

Still just trying to reproduce the original problem which I'm having trouble doing. The url that you tried out on chrome I think is a red herring because it looks to me likes you copied the url over incorrectly.

**Comment by mackaymackay** [comment] 2021-11-11 21:44
@mlandauer yes, it's Bitdefender Internet Security

Trying it once again in Chrome, and clicking directly on the link from my email (as opposed to copy/pasting it), I still get the same message ("the page you're looking for doesn't exist") with that same URL in the search bar, i.e. http://email2.theyvoteforyou.org.au/divisions/senate/2021-10-21/6

**Comment by mlandauer** [comment] 2021-11-15 00:01
@mackaymackay I can see from the email that you copied and pasted above that the link url is http://email2.theyvoteforyou.org.au/l2/523178250/61042728c6b3d51a22915f44ebf242997364ce67?url=%2Fdivisions%2Fsenate%2F2021-10-21%2F6 which is what I would expect it to look like rather than http://email2.theyvoteforyou.org.au/divisions/senate/2021-10-21/6.

Does that make sense?

**Comment by mackaymackay** [comment] 2021-11-15 00:21
@mlandauer yes, for whatever reason, when I right click on the link in the email and copy it, that longer url is what I get (i.e. http://email2.theyvoteforyou.org.au/l2/523178250/61042728c6b3d51a22915f44ebf242997364ce67?url=%2Fdivisions%2Fsenate%2F2021-10-21%2F6), but when I actually click on the email's link, or even just paste that longer url in the search bar, it changes to http://email2.theyvoteforyou.org.au/divisions/senate/2021-10-21/6 and I get that error message.

Even just clicking on the longer url as you've posted it above does the same thing. I click, the url changes and I get this:

![image](https://user-images.githubusercontent.com/6345406/141705002-2439f843-cbe4-41f8-968b-3de934054384.png)

**Comment by mlandauer** [comment] 2021-11-15 00:23
Super weird! Hmm...

**Comment by mackaymackay** [comment] 2022-01-07 02:20
We received an email today from a user about this issue:

> Thanks for the notifications, however just in case you have not been told by someone else, your links trigger all sorts of privacy warnings and seem not to open in https, only http.
>
> Given the attention this project is getting I strongly recommend you work harder to retain the confidence of your subscribers up upping your security game!
>
> And thanks again for the great initiative.

**Comment by mlandauer** [comment] 2022-01-07 05:27
I now see I completely missed what was the core issue here. The problem is that the links in the emails don't have domains in them. Eek! This is bad but should be easily fixed I think. It's no doubt due to some of the hasty fixing and refactoring I've been doing.

**Comment by mlandauer** [comment] 2022-03-07 04:05
I've disabled the custom domain which was set to "email2.theyvoteforyou.org.au" previously. This should mean that the links in the emails on TVFY will show up as cuttlefish.oaf.org.au and hopefully be encrypted. It's a workaround until we implement https://github.com/mlandauer/cuttlefish/issues/409

**Comment by mlandauer** [comment] 2022-06-06 23:25
I've switched the custom domain back on so now the links go via "email2.theyvoteforyou.org.au" as before. However the issue that caused the problem here should be fixed now as most of mlandauer/cuttlefish#409 is implemented

**Closed by mlandauer** 2022-06-06 23:25 UTC
Labels: bug
