### ISSUE TITLE
Remove tests that compare pages with old PHP app

### ISSUE THREAD

**Issue by mario-areias** [openaustralia/theyvoteforyou#1144] opened 2017-04-03 08:44 UTC
We have many regression tests that send requests using the PHP URL format inherited from the original [publicwhip](https://bitbucket.org/publicwhip/publicwhip-v1/).  They are quite useful from a regression standpoint and capture many errors that otherwise would have passed.  However, they are a major barrier for people who want to do their first contribution to TVFY, particularly junior developers.

Here is a list of why they are a bit confusing:

- They use PHP URL format, not the Rails one.
```ruby
    it {compare_static("/division.php?date=2013-03-14&number=1&house=representatives")}
    it {compare_static("/division.php?date=2013-03-14&number=1&house=senate")}
    it {compare_static("/division.php?date=2013-03-14&number=1&house=representatives&display=policies", false, false, "_2")}
    it {compare_static("/division.php?date=2013-03-14&number=1&house=senate&display=policies", false, false, "_2")}
```

- There are too many of them. A superficial search shows us we have 118 of them. Mostly focused on the divisions page
```
 find spec/requests/ -name *.rb | xargs egrep compare_static | wc -l
```
- They test too much. I added a random string at the `app/views/divisions/index.html.haml` and then I ran the tests. This little change broke 61 tests. That's a bit overwhelming for such a small change.

```
Finished in 28.4 seconds (files took 3.3 seconds to load)
428 examples, 61 failures
```

- The error reporting is not good. In order to see the errors, one needs to use `git diff` to verify what has changed.
 ```
  61) DivisionsController#index 
      Failure/Error: raise "Don't match. Writing over file in spec/fixtures/static_pages. Do a git diff."
      
      RuntimeError:
        Don't match. Writing over file in spec/fixtures/static_pages. Do a git diff.
      # ./spec/html_compare_helper.rb:83:in `compare_text'
      # ./spec/html_compare_helper.rb:67:in `compare_static'
      # ./spec/requests/divisions_controller_spec.rb:71:in `block (3 levels) in <top (required)>'
```
- They are not easily reproducible. Due to their nature of saving the changes on the HTML files, if you run the tests twice, the tests will pass.

**Comment by mario-areias** [comment] 2017-04-03 08:49
Some suggestions in how to address that. For every new PR from now one, it is required to have tests. If they overlap with the request tests, we then delete the requests tests. It's a slow approach but it's the safest one, I reckon.

Recently, many tests were added for the `divisions_controller.rb`.  It's quite possible some of them overlap with the requests tests, so it might be a good opportunity to start to delete some of these requests tests.

**Comment by equivalentideas** [comment] 2017-04-04 11:15
I think these are both good ideas @mario-areias thanks for raising this issue. These tests are still really useful because of the lack of unit and feature tests, but they are really confusing. Particularly because:

> They are not easily reproducible. Due to their nature of saving the changes on the HTML files, if you run the tests twice, the tests will pass.

The fact that you need to use git to work with the tests is a really pain, and it's easy to forget how it all works even if you are familiar with it :D.

I think you're approach of doing this incrementally is a really good idea. It'll also help us peel away the regression tests that we don't need and keep the ones we do. We have to be very careful as we do that.

I think also the refactoring work you've been doing is really important. Getting more logic out of views and controllers into easy to test methods (and view helper methods) will really help us see which regression tests we can remove.

**Comment by henare** [comment] 2017-04-12 06:42
I'd say this was a duplicate of #1055 but @mario-areias has done such a great job of writing this one up I'll close #1055 instead and rename this :smile:

**Closed** 2022-06-22 19:53 UTC
Labels: bug, wontfix
